#Location of Spring application context:
contextLocation: "classpath*:context/context-common.xml, classpath*:context/context-simple.xml, classpath*:context/console-context.xml"
#contextLocation: "classpath*:context/context-test.xml, classpath*:context/console-context.xml"

#Used for static resource serving in development mode
assets:
  overrides:
    /: ../../wf-dropwizard/src/main/resources/assets/

#Configuration of actors served by this server:
actorConfig:
  actorPreferences:
    - id: "default"
      timeoutPolicies:
        TASK_START_TO_CLOSE: "TIMEOUT: 15 seconds"

#Task server common properties (will be available as placeholders in spring context):
properties:
  pollDelay: 10
  pollDelayUnit: "SECONDS"
  hz.mancenter.enabled: true
  hz.mancenter.url: "http://172.16.4.111:8080/mancenter-2.6"
  hz.decisions.core.pool.size: 64
  hz.decisions.max.pool.size: 128

#resourceBeans:
#  - taskStarterResource
#  - taskReleaserResource

#Http server configuration:
logging:
    level: WARN
    loggers:
        com.hazelcast: INFO
        ru.taskurotta.dropwizard.server.core: INFO
        ru.taskurotta.server: INFO
        ru.taskurotta.server.recovery.RetryEnqueueRecovery: DEBUG
        ru.taskurotta.test.monkey.AbstractMonkeyAspect: INFO
        ru.taskurotta.dropwizard.hz: DEBUG
        com.yammer: INFO
    file:
        enabled: true
        archive: true
        currentLogFilename: ./logs/service.log
        archivedLogFilenamePattern: ./logs/service-%d.log.gz
        logFormat: "%-4r [%t] %-5p %c - %m%n"

http:
    rootPath: "/rest/*"
    gzip:
        enabled: false
    requestLog:
        console:
            # If true, log requests to stdout.
            enabled: false
        file:
            enabled: false
            archive: true
            currentLogFilename: ./target/logs/requests.log
            archivedLogFilenamePattern: ./target/logs/requests-%d.log.gz
#config can be extended here
#http://dropwizard.codahale.com/manual/core/#configuration-defaults